# Generated by Django 5.0.8 on 2024-08-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_diller_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
