# Generated by Django 5.0.8 on 2024-08-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='User',
        ),
    ]
