# Generated by Django 5.0.8 on 2024-08-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_register_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
